apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: users-app
data:
  # URLs de servicios internos (ajusta el puerto según tu backend)
  BACKEND_SERVICE_URL: "http://users-backend:8000"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5000"
  
  # Configuración general
  ENVIRONMENT: "production"
