apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend
  namespace: users-app
  labels:
    app: users-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-backend
  template:
    metadata:
      labels:
        app: users-backend
    spec:
      containers:
      - name: users-backend
        image: 211865220371.dkr.ecr.us-east-1.amazonaws.com/users-backend:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-env-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
